### PR TITLE
Upgrade resource api version

### PR DESCRIPTION
**Pull request by muralikarthikk**

### CODE REVIEW

**Review by pj-linebaugh — CHANGES_REQUESTED** [review]
When making any changes to the chart, the version be updated.

**Comment by muralikarthikk** [comment]
> When making any changes to the chart, the version be updated.

From the last PR, I got that we don't want to tag a version for every code change. Is that still the case for this particular repo? or Do we use the pre-release versions like Carl suggested? Also, the other tranql chart doesn't seem to use pre-release versions.
I can go ahead and make it  0.3.0-dev1, if agreed upon.

**Comment by cschreep** [comment]
Versions reflect releases. Merges into development branches don't necessitate incrementing the version unless we also publish pre-release versions (which we currently don't do). If we need to publish pre-release versions, then we can do as @muralikarthikk suggested and bump to a pre-release tag. 

Please consult https://semver.org/ for more information on the semantic versioning spec that Helm uses.

**Review by cschreep — APPROVED** [review]
👍🏻

**Review by pj-linebaugh — APPROVED** [review]

**Pull request merged**
